name: Secretos

on:
  pull_request:
  push:
    branches: [main]

jobs:
  secretos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: trufflesecurity/trufflehog@v3
        with:
          path: ./
          base: ""
          head: ""
          extra_args: --only-verified
